### ISSUE TITLE
ScopedMetrics is unsafe to use if uninitialized.

### ISSUE THREAD

**Issue by dainstber** [awslabs/swage#6]
Library code cannot utilize ScopedMetrics in its current state. There is no way for a library to tell if ScopedMetrics has been initialized or a context has been opened. Attempting to open ScopedMetrics will result in an IllegalStateException. Attempting to record on an unopened metric will result in a NPE. As a library I cannot assume that all of my clients will have initialized SwageMetrics. It would be better to have ScopedMetrics handle these cases rather than expecting every library to implement this exception handling.

**Comment by jerpowers** [comment]
What would be the desired behavior if someone uses your library without configuring ScopedMetrics?
Current implementation is intended to require the application level code to initialize it.  Would you prefer the metrics calls to result in a no-op if it is not initialized, or some other behavior?

If a library requires initialization, it is arguably an error to use said library without initialization.  Using ScopeMetrics in a library adds the requirement of initializing the metrics properly for the library.  If your library uses log4j, for example, you must assume users of the library will initialize logging properly.

**Comment by dainstber** [comment]
With Log4j, a library can program against the API, and if an application does not provide an implementation, log4j will default to using the SimpleLogger. It will record an error log telling you that it is not correctly initialized, but the application will continue execution. 

I cannot think of a case where failures in logging or recording metrics should break the application flow.  Unlike logging, there is no default channel for recording metrics. I would expect these to log a warning or an error, but not throw an exception.

**Comment by dainstber** [comment]
This was addressed in ThreadLocalMetrics
